CREATE TABLE Departments (
	DepID VARCHAR(20) PRIMARY KEY,
	name NVARCHAR(200),
	OFFICE NVARCHAR(100)
)

CREATE TABLE Employees (
	EmpCode VARCHAR(20) PRIMARY KEY,
	Name NVARCHAR(50),
	BirthDate DATE,
	DepID VARCHAR(20),
	CONSTRAINT BelongTo FOREIGN KEY (DepID) REFERENCES Departments(DepID)
)

CREATE TABLE Dependants (
	Number INT PRIMARY KEY,
	Name NVARCHAR(50),
	BirthDate DATE,
	Role NVARCHAR(30),
	EmpCode VARCHAR(20),
	CONSTRAINT has FOREIGN KEY (EmpCode) REFERENCES Employees(EmpCode)
)