DROP TABLE IF EXISTS CTphieumuon;
DROP TABLE IF EXISTS SACH;
DROP TABLE IF EXISTS LOAISACH;
DROP TABLE IF EXISTS PHIEUMUON;
DROP TABLE IF EXISTS SINHVIEN;
DROP TABLE IF EXISTS THESINHVIEN;

CREATE TABLE LOAISACH (
	MALOAI nvarchar(30) primary key,
	TENLOAI nvarchar(30)
)

CREATE TABLE SACH (
	MASACH nvarchar(30) PRIMARY KEY,
	TENSACH nvarchar(30),
	SOTRANG INT CHECK(SOTRANG > 5),
	MALOAI nvarchar(30),
	CONSTRAINT NN FOREIGN KEY(MALOAI) References LOAISACH(MALOAI)
)

CREATE TABLE THESINHVIEN (
	MASV NVARCHAR(8) PRIMARY KEY,
	TENSV NVARCHAR(30),
	NGAYHH DATE,
	MAJOR NVARCHAR(40)
)

CREATE TABLE SINHVIEN (
	MASV NVARCHAR(8) PRIMARY KEY References THESINHVIEN(MASV),
	EMAIL NVARCHAR(30) UNIQUE,
	PHONE NVARCHAR(30) UNIQUE
)

CREATE TABLE PHIEUMUON (
	MAPM NVARCHAR(30) PRIMARY KEY,
	MASV NVARCHAR(8),
	CONSTRAINT NNN FOREIGN KEY(MASV) references SINHVIEN(MASV)
)

/* Chi tiet phieu muon */
CREATE TABLE CTphieumuon ( 
	MAPM NVARCHAR(30),
	MASACH NVARCHAR(30),
	SL INT,
	NGAYMUON DATE,
	PRIMARY KEY (MAPM, MASACH), 
	CONSTRAINT NNNN FOREIGN KEY(MAPM) references PHIEUMUON(MAPM),
	CONSTRAINT NNNNN FOREIGN KEY(MASACH) references SACH(MASACH)
)